In [100]:
import numpy as np

In [52]:
# Speed check

# list
a1 = [i for i in range(10000000)]
a2 = [i for i in range(10000000, 20000000)]

c = []

import time;
start = time.time()

for i in range(len(a1)):
    c.append(a1[i] + a2[i])

print(time.time() - start)

# numpy
b1 = np.arange(10000000)
b2 = np.arange(10000000, 20000000)

start1 = time.time()
c1 = b1 + b2
print(time.time() - start1)

1.8483860492706299
0.033457040786743164


In [53]:
# Allocate Memory

a1 = [i for i in range(10000000)]
b1 = np.arange(10000000, dtype = np.int8);

import sys
print(sys.getsizeof(a1))
print(sys.getsizeof(b1))

89095160
10000112


In [54]:
# Fancy indexing

a = np.arange(24).reshape(6, 4)
print(a)
print(a[[0, 2, 3, 5]])
print(a[:, [0, 1, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]
 [12 13 15]
 [16 17 19]
 [20 21 23]]


In [95]:
# Boolean indexing

# Random generate int
a = np.random.randint(1, 100, 24).reshape(6, 4)
a[a > 50]
a[a % 2 == 0]
a[(a > 50) & (a % 2 == 0)]
a[a % 7 != 0]

array([55, 78, 16, 16,  5, 69, 78, 90, 74, 47, 24, 13, 12, 16, 17, 23, 20,
       19, 94, 68])

In [115]:
# Broadcasting

# Same shape
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

# print(a + b)

# Different shape
a = np.arange(6).reshape(2, 3)
b = np.arange(3)

# Example - 1
a = np.arange(12).reshape(4, 3)
b = np.arange(3).reshape(3)

print(a + b) # possible

# Example - 2
a = np.arange(12).reshape(3, 4)
b = np.arange(3).reshape(3)

# print(a+b) impossible

# Example - 3
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)

print(a + b) # possible

# Example - 4
a = np.arange(3).reshape(1, 3)
b = np.arange(4).reshape(4, 1)

print(a + b) # possible

# Example - 5
a = np.arange(12).reshape(3, 4)
b = np.arange(12).reshape(4, 3)

# print(a + b) impossible

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]
