**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here

a = np.nan * np.empty(10)
a[4] = 1
print(a)

[nan nan nan nan  1. nan nan nan nan nan]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [27]:
#Code here

a = (int)(input("Enter first value: "))
b = (int)(input("Enter second value: "))

p = np.random.random((a, b))
print(p)
print(p.mean())

[[0.05997324 0.91038527 0.5096725 ]
 [0.94132405 0.26017443 0.03890215]]
0.4534052730357612


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [46]:
#Code here
def borderArray(a, b):
    x = np.ones((a, b))
    x[1:-1, 1:-1] = 0
    print(x)

borderArray(6, 7)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [53]:
#Code here
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [54]:
#Code here
# in identity matrix row == col hence (3, 4) not possible

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [57]:
#Code here
a = np.zeros((5, 5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [83]:
#code here
a = np.random.randint(1, 100, (10, 2))
point = np.array([2, 3])
distance = np.sqrt(np.sum((a - point) ** 2, axis = 1)).astype(int)
print(a)
print(point)
print(distance)

[[ 7 12]
 [95 82]
 [64 57]
 [ 9 85]
 [40 31]
 [36  7]
 [41 94]
 [12 81]
 [28 76]
 [80 89]]
[2 3]
[ 10 122  82  82  47  34  99  78  77 116]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [85]:
#Code here
a = np.unravel_index(100, (6, 7, 8))
print(a)

(np.int64(1), np.int64(5), np.int64(4))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [86]:
#Code here
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

array([-10.,  -8.,   5.,   3.,   2.,   1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [90]:
#Code here
a = np.array([])
b = np.array([1, 2])
c = np.ones((2, 3))
print(a.size)
print(b.size)
print(c.size)

0
2
6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

def softMax(npArr):
    if type(npArr) != np.ndarray:
        raise TypeError("Allow only numpy array")
    
    elif npArr.ndim > 1:
        raise TypeError("Allow only 1d array")
    
    s = np.sum(np.exp(npArr))
    return np.exp(npArr) / s 

softMax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

def infiniteNum(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Only numpy array")
        return np.vstack(args)
    
a = np.arange(1, 11).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.random.random((2,5))

infiniteNum(a, b, c)

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 6.        ,  7.        ,  8.        ,  9.        , 10.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.57901031,  0.93845727,  0.63602497,  0.85350914,  0.02522376],
       [ 0.95700281,  0.54304887,  0.21181515,  0.13738525,  0.33772849]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str  or type(end) != str:
        raise TypeError("Only string accept")
    
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split('-')
    end_last = (int)(end[-1]) + 1

    if total_days_of_month[end[-2]] < end_last:
        diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{diff}' if diff < 10 else f'{diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month < 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'

    end = "-".join(end)
    return np.arange(start, end, dtype = "datetime64[D]")

date_array(start = '2020-01-25', end = '2020-01-30')

array(['2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
x = np.random.random((5, 4))
x - x.mean(axis = 1, keepdims=True)

array([[-0.01429588,  0.30421196, -0.07085934, -0.21905674],
       [-0.07271391,  0.28955972,  0.12500292, -0.34184874],
       [-0.09956377,  0.37537898,  0.05497767, -0.33079288],
       [ 0.1812194 , -0.30078451, -0.15842605,  0.27799116],
       [-0.28195515,  0.04495962,  0.04495109,  0.19204444]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [151]:
#Code here
a = np.arange(1, 10).reshape(3, 3)
print(a)
a[:, [0, 2, 1]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 3, 2],
       [4, 6, 5],
       [7, 9, 8]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
a = np.arange(1, 10).reshape(3, 3)
print(a)
a[a %  2 == 1] = -1
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

np.maximum(a, b)


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [163]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1073, 1613, 5384,   42, 5540],
       [5778, 2073, 5138, 4579, 1619],
       [3931, 2540, 5315, 7526, 2719],
       [6727, 3023, 8686, 8540, 1314],
       [2965, 4851, 6513, 6953, 4923],
       [6880, 2481, 3733, 3159, 9821],
       [2453, 5739, 5329, 1172, 7727],
       [ 573, 2938,  897, 2455, 9644]], dtype=int32)

In [165]:
#Code here
arr1[:, ::2]
(arr1 - arr1.min()) / (arr1.max() - arr1.min())

array([[0.10543   , 0.16065037, 0.54627263, 0.        , 0.56222518],
       [0.58656304, 0.20768995, 0.52111668, 0.46395337, 0.16126393],
       [0.39768893, 0.25544534, 0.53921669, 0.76531343, 0.27374987],
       [0.68360773, 0.3048369 , 0.88393496, 0.86900501, 0.13007465],
       [0.29890582, 0.49176807, 0.6617241 , 0.70671848, 0.49913079],
       [0.6992535 , 0.24941201, 0.37744146, 0.31874425, 1.        ],
       [0.24654873, 0.58257491, 0.54064833, 0.11555374, 0.78586768],
       [0.05430003, 0.2961448 , 0.08743225, 0.24675325, 0.98189999]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [169]:
#Code here

def nthLarge(arr, n):
    if len(arr) < n:
        raise IndexError("len(arr) >= n")
    arr.sort()
    return arr[-n]

nthLarge(np.array([12,34,40,7,1,0]), 3)

np.int64(12)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1, 2, 3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])