In [2]:
import numpy as np # type: ignore

In [3]:
# create numpy array

a = np.array([1, 2, 3, 4])
print(a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [4]:
# 2d(matrix) & 3d(tensor) -> pass list

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b, type(b))

c = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(c, type(c))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [5]:
# own data type (dtype)

a = np.array([1, 2, 3], dtype = float)
a = np.array([1, 2, 3], dtype = bool)
a = np.array([1, 2, 3], dtype = complex)
print(a, type(a))

[1.+0.j 2.+0.j 3.+0.j] <class 'numpy.ndarray'>


In [6]:
# np array in range (arange)

a = np.arange(1, 13)
print(a, type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>


In [7]:
# array size convert (reshape) -> size multiplication = total number of element

a = np.arange(1, 13).reshape(2, 6) 
b = np.arange(16).reshape(2, 2, 2, 2)
print(a, type(a))
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] <class 'numpy.ndarray'>
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [8]:
# initial matrix(ones, zeros) -> pass size as tuple 

a = np.ones((3, 4))
b = np.zeros((3, 4))
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# random size(pass tuple) matrix with value (0-1)

a = np.random.random((4, 3))
print(a)

[[0.00198745 0.6895488  0.84601869]
 [0.2761807  0.27106039 0.11023469]
 [0.83956679 0.144059   0.1803812 ]
 [0.99425268 0.69972397 0.57563763]]


In [10]:
# value with equal distance (linspace)

a = np.linspace(-12, 12, 7)
print(a)

[-12.  -8.  -4.   0.   4.   8.  12.]


In [11]:
# identity matrix

a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

# .ndim for dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

# .shape for every value in each dim
print(a1.shape)
print(a2.shape)
print(a3.shape)

# .size for total number of element 
print(a1.size)
print(a2.size)
print(a3.size)

# .itemsize for memory occupy of each element
print("a1", a1.itemsize)
print(a2.itemsize)

1
2
3
(10,)
(3, 4)
(2, 2, 2)
10
12
8
a1 4
8


In [13]:
# .astype for change memory size

a = np.arange(12, dtype = np.int64).reshape(3, 4)
a = a.astype(np.int32)
print(a.dtype)

int32


In [14]:
# scalar operation

# arithmetic
a = np.arange(12).reshape(3, 4)
a = a * 2
a = a + 2
a = a - 2
a = a / 2
a = a ** 2

# relational
a = a > 5
a = a < 1
a = a == 1
print(a)

[[ True  True  True False]
 [False False False False]
 [False False False False]]


In [15]:
# vector operation

a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(1, 13).reshape(3, 4)

a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 ** a2

array([[          0,           1,           8,          81],
       [       1024,       15625,      279936,     5764801],
       [  134217728,  -808182895,  1215752192, -1192716655]])

In [13]:
# Array operation

a1 = np.random.randint(1, 100, 12).reshape(3, 4)
a2 = np.random.random((3, 4))

print(a1)
print(a2)

np.max(a1)
np.min(a1)
np.sum(a1) # sum of all number in array
np.prod(a1) # product of all number in array

print(np.max(a1, axis = 0)) # row wise all max value
print(np.max(a1, axis = 1)) # col wise all max value

[[63 18 26 30]
 [86 14 71 33]
 [43  1 54 83]]
[[0.48762158 0.73761981 0.46280063 0.13334333]
 [0.97490294 0.67236549 0.9787135  0.0061217 ]
 [0.35503448 0.4452208  0.87538143 0.22241651]]
[86 18 71 83]
[63 86 83]


In [16]:
# Statistical calculation

a1 = np.arange(10, 22).reshape(3, 4)
print(a1)

# mean -> sum of all value / total element
np.mean(a1)
np.mean(a1, axis = 0) # row wise mean

# median -> middle value
np.median(a1, axis = 1) # col wise median

# mode -> that appear most
# std -> standard deviation
# np.std(a1, axis = 1)

# var -> variance 
# np.var(a1, axis = 0)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([14., 15., 16., 17.])

In [18]:
# Trigonometric function

a1 = np.arange(12).reshape(3, 4)
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [19]:
# Dot product -> matrix multiplication

a1 = np.arange(2, 8).reshape(3, 2)
a2 = np.arange(1, 7).reshape(2, 3)

print(a1)
print(a2)

np.dot(a1, a2)
np.dot(a2, a1)

[[2 3]
 [4 5]
 [6 7]]
[[1 2 3]
 [4 5 6]]


array([[28, 34],
       [64, 79]])

In [20]:
# Logarithmic and exponential

a1 = np.arange(1, 7).reshape(3, 2)
np.log(a1)
np.exp(a1)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [21]:
a1 = np.random.random((3,4)) * 100
print(a1)

# round
np.round(a1)

# floor
np.floor(a1)

# ceil
np.ceil(a1)

[[66.49721671 73.02663286 99.26442161 58.08065561]
 [37.37112358 33.65278639 97.81140025 37.64761107]
 [41.70744247 58.88097108 74.35050622 26.2917104 ]]


array([[ 67.,  74., 100.,  59.],
       [ 38.,  34.,  98.,  38.],
       [ 42.,  59.,  75.,  27.]])

In [38]:
# Indexing

a1 = np.arange(12)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

print(a1)
print(a2)
print(a3)

print(a1[-1])
print(a1[2])

print(a2[1, 2])
print(a2[2, 1])

print(a3[1, 0, 1])
print(a3[0, 1, 1])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
11
2
6
9
5
3


In [85]:
# Slicing

# 1D array
a1 = np.arange(12)
# print(a1[2:5:2]) # [include:exclude:jump 2 means 1]

# 2D array
a2 = np.arange(12).reshape(3, 4)
# print(a2[1, :]) # 2nd row all col
# print(a2[:, 0:1]) # all row 1st col
# print(a2[1:, 1:3])
# print(a2[::2, ::3])
# print(a2[::2, 1::2])
# print(a2[1, 0::3])
# print(a2[0:2, 1:])

# 3D array
a3 = np.arange(27).reshape(3, 3, 3)
print(a3)
# print('\n')
# print(a3[1])
# print(a3[::2])
# print(a3[0, 1, :])
# print(a3[1, :, 1])
# print(a3[2, 1:, 1:])
print(a3[::2, 0, ::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  2]
 [18 20]]


In [4]:
# Iterating

# 1D array
a1 = np.arange(12)
# for i in a1:
#     print(i)

# 2D array
a2 = np.arange(12).reshape(3, 4)
# for i in a2:
#     print(i)
#     for j in i:
#         print(j)

# 3D array
# Rule - 01
a3 = np.arange(27).reshape(3, 3, 3)
# for i in a3:
#     for j in i:
#         for k in j:
#             print(k)

# Rule - 02
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [51]:
# Transpose

a2 = np.arange(12).reshape(3, 4)
np.transpose(a2) # R-1
a2.T # R-2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [53]:
# Ravel -> an dimension to 1D 

a3 = np.arange(27).reshape(3, 3, 3)
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [122]:
# Stacking -> pass tuple 

# Horizontal stack 
b1 = np.arange(12).reshape(3, 4)
b2 = np.arange(12, 24).reshape(3, 4)

print(np.hstack((b1, b2)))

# Vertical stack
print(np.vstack((b1, b2)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [123]:
# Splitting -> split in same part

# Horizontal split
b2 = np.arange(12, 24).reshape(3, 4)
print(b2)
np.hsplit(b2, 2)

# Vertical split
np.vsplit(b2, 3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]