In [1]:
import numpy as np # type: ignore

In [2]:
# create numpy array

a = np.array([1, 2, 3, 4])
print(a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [3]:
# 2d(matrix) & 3d(tensor) -> pass list

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b, type(b))

c = np.array([[
    [1, 2],
    [3, 4],
    [5, 6]
]])
print(c, type(c))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[[1 2]
  [3 4]
  [5 6]]] <class 'numpy.ndarray'>


In [4]:
# own data type (dtype)

a = np.array([1, 2, 3], dtype = float)
b = np.array([1, 2, 3], dtype = bool)
c = np.array([1, 2, 3], dtype = complex)
print(c, type(c))

[1.+0.j 2.+0.j 3.+0.j] <class 'numpy.ndarray'>


In [5]:
# np array in range (arange)

a = np.arange(1, 13)
print(a, type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>


In [6]:
# array size convert (reshape) -> size multiplication = total number of element

a = np.arange(1, 13).reshape(2, 6) 
b = np.arange(16).reshape(2, 2, 2, 2)
print(a, type(a))
print(b)

x = np.arange(1, 10).reshape(-1, 1) # 9 row 1 col
x = np.arange(1, 10).reshape(1, -1) # 1 row 9 col
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] <class 'numpy.ndarray'>
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[1 2 3 4 5 6 7 8 9]]


In [7]:
# initial matrix(ones, zeros) -> pass size as tuple 

a = np.ones((3, 4))
b = np.zeros((3, 4))
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# random size(pass tuple) matrix with value (0-1)

a = np.random.random((4, 3))
print(a)

[[0.47210691 0.2786133  0.67739565]
 [0.85154727 0.39954373 0.9959597 ]
 [0.35873472 0.66997652 0.54327891]
 [0.73044559 0.60282619 0.04643697]]


In [9]:
# value with equal distance (linspace)

a = np.linspace(-12, 12, 7)
print(a)

[-12.  -8.  -4.   0.   4.   8.  12.]


In [10]:
# identity matrix

a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

# .ndim for dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

# .shape for every value in each dim
print(a1.shape)
print(a2.shape)
print(a3.shape)

# .size for total number of element 
print(a1.size)
print(a2.size)
print(a3.size)

# .itemsize for memory occupy of each element
print("a1 -> ", a1.itemsize)
print(a2.itemsize)

1
2
3
(10,)
(3, 4)
(2, 2, 2)
10
12
8
a1 ->  8
8


In [12]:
# .astype for change memory size

a = np.arange(12, dtype = np.int64).reshape(3, 4)
b = a.astype(np.int8)
print(a.dtype)
print(b.dtype)

int64
int8


In [13]:
# scalar operation

# arithmetic
a = np.arange(12).reshape(3, 4)
a = a * 2
a = a + 2
a = a - 2
a = a / 2
a = a ** 2

print(a)

# relational
a > 5
a < 1
a == 1
print(a == 1)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]]
[[False  True False False]
 [False False False False]
 [False False False False]]


In [14]:
# vector operation

a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(1, 13).reshape(3, 4)

a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 ** a2

array([[            0,             1,             8,            81],
       [         1024,         15625,        279936,       5764801],
       [    134217728,    3486784401,  100000000000, 3138428376721]])

In [15]:
# Array operation

a1 = np.random.randint(1, 100, 12).reshape(3, 4)
a2 = np.random.random((3, 4))

print(a1)
print(a2)

np.max(a1)
np.min(a1)
np.sum(a1) # sum of all number in array
np.prod(a1) # product of all number in array

print(np.max(a1, axis = 0)) # row wise all max value
print(np.max(a1, axis = 1)) # col wise all max value

[[ 2 61 45 89]
 [66 16 30 82]
 [63 51  7 77]]
[[0.79656447 0.09129063 0.62362934 0.28713915]
 [0.61748914 0.40967501 0.26771605 0.88458253]
 [0.50687645 0.63560908 0.20933436 0.35637206]]
[66 61 45 89]
[89 82 77]


In [16]:
# Statistical calculation

a1 = np.arange(10, 22).reshape(3, 4)
print(a1)

# mean -> sum of all value / total element
np.mean(a1)
np.mean(a1, axis = 0) # row wise mean

# median -> middle value
np.median(a1, axis = 1) # col wise median

# mode -> that appear most
# std -> standard deviation
np.std(a1, axis = 1)

# var -> variance 
np.var(a1, axis = 0)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [17]:
# Trigonometric function

a1 = np.arange(12).reshape(3, 4)
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [18]:
# Dot product -> matrix multiplication

a1 = np.arange(2, 8).reshape(3, 2)
a2 = np.arange(1, 7).reshape(2, 3)

print(a1)
print(a2)

np.dot(a1, a2)
np.dot(a2, a1)

[[2 3]
 [4 5]
 [6 7]]
[[1 2 3]
 [4 5 6]]


array([[28, 34],
       [64, 79]])

In [19]:
# Logarithmic and exponential

a1 = np.arange(1, 7).reshape(3, 2)
np.log(a1)
np.exp(a1)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [20]:
a1 = np.random.random((3,4)) * 100
print(a1)

# round
np.round(a1)

# floor
np.floor(a1)

# ceil
np.ceil(a1)

[[74.53475757 95.43545551 78.70931272 31.94590122]
 [45.2051151   8.11277423 29.96283378 49.97569747]
 [79.60955767 23.15166877 49.58469217 61.69926431]]


array([[75., 96., 79., 32.],
       [46.,  9., 30., 50.],
       [80., 24., 50., 62.]])

In [21]:
# Indexing

a1 = np.arange(12)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

print("a1", a1)
print("a2", a2)
print("a3", a3)

print(a1[-1])
print(a1[2])

print(a2[1, 2])
print(a2[2, 1])

print(a3[1, 0, 1])
print(a3[0, 1, 1])

a1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
11
2
6
9
5
3


In [22]:
# Slicing

# 1D array
a1 = np.arange(12)
print(a1)
print(a1[2:5:2]) # [include:exclude:jump 2 means 1]

# 2D array
a2 = np.arange(12).reshape(3, 4)
print(a2)
print(a2[1, :]) # 2nd row all col
print(a2[:, 0:1]) # all row 1st col
print(a2[1:, 1:3])
print(a2[::2, ::3])
print(a2[::2, 1::2])
print(a2[1, 0::3])
print(a2[0:2, 1:])

# 3D array
a3 = np.arange(27).reshape(3, 3, 3)
print(a3)
print(a3[1])
print(a3[::2])
print(a3[0, 1, :])
print(a3[1, :, 1])
print(a3[2, 1:, 1:])
print(a3[::2, 0, ::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[[0]
 [4]
 [8]]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [23]:
# Iterating

# 1D array
a1 = np.arange(12)
# for i in a1:
#     print(i)

# 2D array
a2 = np.arange(12).reshape(3, 4)
# for i in a2:
#     print(i)
#     for j in i:
#         print(j)

# 3D array
# Rule - 01
a3 = np.arange(27).reshape(3, 3, 3)
# for i in a3:
#     for j in i:
#         for k in j:
#             print(k)

# Rule - 02
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [24]:
# Transpose

a2 = np.arange(12).reshape(3, 4)
print(a2)
np.transpose(a2) # R-1
a2.T # R-2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [25]:
# Ravel -> any dimension to 1D 

a3 = np.arange(27).reshape(3, 3, 3)
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [26]:
# Stacking -> pass tuple 

# Horizontal stack 
b1 = np.arange(12).reshape(3, 4)
b2 = np.arange(12, 24).reshape(3, 4)

print(b1)
print(b2)

print(np.hstack((b1, b2)))

# Vertical stack
print(np.vstack((b1, b2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
# Splitting -> split in same part

# Horizontal split
b2 = np.arange(12, 24).reshape(3, 4)
print(b2)

np.hsplit(b2, 2)

# Vertical split
np.vsplit(b2, 3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]