In [2]:
import numpy as np # type: ignore

In [3]:
# create numpy array

a = np.array([1, 2, 3, 4])
print (a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [4]:
# 2d(matrix) & 3d(tensor) -> pass list

b = np.array([[1, 2, 3], [4, 5, 6]])
print (b, type(b))

c = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print (c, type(c))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [5]:
# own data type (dtype)

a = np.array([1, 2, 3], dtype = float)
a = np.array([1, 2, 3], dtype = bool)
a = np.array([1, 2, 3], dtype = complex)
print (a, type(a))

[1.+0.j 2.+0.j 3.+0.j] <class 'numpy.ndarray'>


In [6]:
# np array in range (arange)

a = np.arange(1, 13)
print (a, type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>


In [7]:
# array size convert (reshape) -> size multiplication = total number of element

a = np.arange(1, 13).reshape(2, 6) 
b = np.arange(16).reshape(2, 2, 2, 2)
print (a, type(a))
print (b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] <class 'numpy.ndarray'>
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [8]:
# initial matrix(ones, zeros) -> pass size as tuple 

a = np.ones((3, 4))
b = np.zeros((3, 4))
print (a)
print (b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# random size(pass tuple) matrix with value (0-1)

a = np.random.random((4, 3))
print (a)

[[0.91900947 0.99471217 0.74485358]
 [0.25574839 0.85518965 0.3876814 ]
 [0.54864791 0.27520742 0.24025904]
 [0.04813873 0.60830849 0.14815501]]


In [10]:
# value with equal distance (linspace)

a = np.linspace(-12, 12, 7)
print (a)

[-12.  -8.  -4.   0.   4.   8.  12.]


In [11]:
# identity matrix

a = np.identity(5)
print (a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

# .ndim for dimension
print (a1.ndim)
print (a2.ndim)
print (a3.ndim)

# .shape for every value in each dim
print (a1.shape)
print (a2.shape)
print (a3.shape)

# .size for total number of element 
print (a1.size)
print (a2.size)
print (a3.size)

# .itemsize for memory occupy of each element
print("a1", a1.itemsize)
print(a2.itemsize)

1
2
3
(10,)
(3, 4)
(2, 2, 2)
10
12
8
a1 4
8


In [13]:
# .astype for change memory size

a = np.arange(12, dtype = np.int64).reshape(3, 4)
a = a.astype(np.int32)
print (a.dtype)

int32


In [14]:
# scalar operation

# arithmetic
a = np.arange(12).reshape(3, 4)
a = a * 2
a = a + 2
a = a - 2
a = a / 2
a = a ** 2

# relational
a = a > 5
a = a < 1
a = a == 1
print (a)

[[ True  True  True False]
 [False False False False]
 [False False False False]]


In [15]:
# vector operation

a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(1, 13).reshape(3, 4)

a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 ** a2

array([[          0,           1,           8,          81],
       [       1024,       15625,      279936,     5764801],
       [  134217728,  -808182895,  1215752192, -1192716655]])

In [16]:
# Array operation

a1 = np.arange(1, 13).reshape(3, 4)
a2 = np.random.random((3, 4))

print (a1)
print (a2)

np.max(a1)
np.min(a1)
np.sum(a1) # sum of all number in array
np.prod(a1) # product of all number in array

np.max(a1, axis = 0) # column wise all max value
np.max(a1, axis = 1) # row wise all max value

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0.80013789 0.12876528 0.98308043 0.61645207]
 [0.00364045 0.8445353  0.04073348 0.00551325]
 [0.9926773  0.99001655 0.76670554 0.77625467]]


array([ 4,  8, 12])

In [17]:
# Statistical calculation

a1 = np.arange(10, 22).reshape(3, 4)
print(a1)

# mean -> sum of all value / total element
np.mean(a1)
np.mean(a1, axis = 0) # col wise mean

# median -> middle value
np.median(a1, axis = 1) # row wise median

# mode -> that appear most
# std -> standard deviation
np.std(a1, axis = 1)

# var -> variance 
np.var(a1, axis = 0)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [18]:
# Trigonometric function

a1 = np.arange(12).reshape(3, 4)
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [19]:
# Dot product -> matrix multiplication

a1 = np.arange(2, 8).reshape(3, 2)
a2 = np.arange(1, 7).reshape(2, 3)

print (a1)
print (a2)

np.dot(a1, a2)
np.dot(a2, a1)

[[2 3]
 [4 5]
 [6 7]]
[[1 2 3]
 [4 5 6]]


array([[28, 34],
       [64, 79]])

In [20]:
# Logarithmic and exponential

a1 = np.arange(1, 7).reshape(3, 2)
np.log(a1)
np.exp(a1)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [21]:
a1 = np.random.random((3,4)) * 100
print (a1)

# round
np.round(a1)

# floor
np.floor(a1)

# ceil
np.ceil(a1)

[[24.26009033 89.75976353 34.40458573 24.20976758]
 [61.06231548 78.70797453 81.69843087 59.51180674]
 [29.42757037 16.95002149 72.77437147 39.97495344]]


array([[25., 90., 35., 25.],
       [62., 79., 82., 60.],
       [30., 17., 73., 40.]])