In [1]:
import numpy as np # type: ignore

In [ ]:
# Sorting

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.sort(a) # sort in ascending
np.sort(a)[::-1] # sort in descending

np.sort(b) # row wise sorting
print(b)
np.sort(b, axis = 0) # row wise sorting
np.sort(b, axis = 1) # col wise sorting

[[31  8 79 20]
 [20 38 34 90]
 [64 55 12 89]
 [39 20  3 53]
 [98  5 85 74]
 [66 42 54 56]]


array([[ 8, 20, 31, 79],
       [20, 34, 38, 90],
       [12, 55, 64, 89],
       [ 3, 20, 39, 53],
       [ 5, 74, 85, 98],
       [42, 54, 56, 66]], dtype=int32)

In [3]:
# Append

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.append(a, 202) # append 202 as last element in a 
print(b.shape[0])
np.append(b, np.ones((b.shape[0], 1)), axis = 1) # append 1 in last col

6


array([[91., 85., 10., 56.,  1.],
       [94., 97., 82., 19.,  1.],
       [72., 45., 61., 22.,  1.],
       [48., 62.,  1.,  2.,  1.],
       [83., 72., 63., 44.,  1.],
       [43., 15., 62., 65.,  1.]])

In [4]:
# Concatenate

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print(a)
print(b)

np.concatenate((a, b), axis = 0) # row wise -> vstack
np.concatenate((a, b), axis = 1) # col wise -> hstack

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [5]:
# Unique item

a = np.array([1, 2, 1, 2, 4, 5, 6, 5, 7, 9, 7, 3, 2])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [6]:
# Expand dimension

a = np.arange(1, 7).reshape(3, 2)
print(a)
print('\n')
b = np.expand_dims(a, axis = 0)
c = np.expand_dims(a, axis = 1)
# print(a.shape, b.shape)

print(b)
print('\n')
print(c)

[[1 2]
 [3 4]
 [5 6]]


[[[1 2]
  [3 4]
  [5 6]]]


[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [7]:
# Where value satisfy

a = np.random.randint(1, 100, 20)
np.where(a > 50) # return index only value > 50
np.where(a > 50, 0, 1) # replace 0 where true and replace 1 where false

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1])

In [8]:
# Argmax / Argmin -> return max/min value index

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)
np.argmax(a) # max value index
np.argmin(a) # min value index

np.argmax(b, axis = 0)
np.argmin(b, axis = 1)

[ 3  4 62 83 59 48 22 91 74 86]
[[ 2 13 76 55]
 [96 12 82  4]
 [ 2 94  8 17]]


array([0, 3, 0])

In [9]:
# Cumsum & Cumprod -> sum of previous all

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.cumsum(a)
np.cumprod(a)

np.cumsum(b, axis = 0) # row
np.cumprod(b, axis = 1) # col

[42  1 11 76 61 54  6  5 31 37]
[[21 52 74 63]
 [78 73 55 96]
 [64 63 56 27]]


array([[      21,     1092,    80808,  5090904],
       [      78,     5694,   313170, 30064320],
       [      64,     4032,   225792,  6096384]])

In [10]:
# Percentile -> how many % people behind me

a = np.random.randint(1, 100, 10)
print(a)

print(np.sort(a))
np.percentile(a, 0) # min
np.percentile(a, 50) # mid
np.percentile(a, 100) # max

[35 63 38 91 42 98 53 96 65 32]
[32 35 38 42 53 63 65 91 96 98]


np.float64(98.0)

In [11]:
# Histogram -> frequency count in given range (bins)
    
a = np.random.randint(1, 100, 50)
print(a)
np.histogram(a, bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

[84 55 79 53 88 49 12 77 62 37 34 52 50 22 87 22 91 12 52 30 61 16 85 40
 80 40 99 16 39 37  6 78 39 43 90 98 26 34 27 93 66 69 56 43 76 88 40 19
 96 37]


(array([1, 5, 4, 8, 6, 6, 4, 4, 6, 6]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [12]:
# Corelation (ans lie in -1 to 1) & Coefficient

salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [13]:
# Isin -> search for multiple item

a = np.random.randint(1, 100, 20);
items = np.array([10, 20, 30, 40, 50, 60, 70])

print(a)
print(items)
np.isin(a, items)
a[np.isin(a, items)]

[82 66  9 53 83 75 87 30 33 60 62 86 25 49 68 79 46 70 98 45]
[10 20 30 40 50 60 70]


array([30, 60, 70], dtype=int32)

In [14]:
# Flip -> reverse

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.flip(a)
np.flip(b) # row, col flip
np.flip(b, axis = 0) # row flip
np.flip(b, axis = 1) # col flip

[62 55 79 25 97 46 54 98 61 70]
[[66 24 47 59]
 [78 91 36 83]
 [90 74 79 22]]


array([[59, 47, 24, 66],
       [83, 36, 91, 78],
       [22, 79, 74, 90]], dtype=int32)

In [15]:
# Put -> replace specific element

a = np.random.randint(1, 100, 10)
print(a)

np.put(a, [0, 5, 2], [100, 200, 300])
a

[ 9 23 68 42 11 59 69 85 25 55]


array([100,  23, 300,  42,  11, 200,  69,  85,  25,  55], dtype=int32)

In [16]:
# Delete -> after delete return new array

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.delete(a, 0)
np.delete(a, [0, 2, 3])
np.delete(b, 0, axis = 0)

[86 71 62 80 73 85 91  7  8 12]
[[59 65 62 23]
 [64 34 94 19]
 [39  5 16 92]]


array([[64, 34, 94, 19],
       [39,  5, 16, 92]], dtype=int32)

In [17]:
# Set function

m = np.array([1, 2, 3, 4, 5, 6])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)
np.intersect1d(m, n)
np.setdiff1d(m, n) # element in m not n
np.setxor1d(m, n) # remove common element
np.in1d(m, 2)

C:\Users\Asus\AppData\Local\Temp\ipykernel_10536\1598237902.py:10: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m, 2)


array([False,  True, False, False, False, False])

In [18]:
# Clip -> value in range

b = np.random.randint(1, 100, 20)
print(b)
np.clip(b, a_min = 5, a_max = 66)

[55 87 63 13 59  1 86 59 79 88 79 64 89 25 83 36 67 43 12 40]


array([55, 66, 63, 13, 59,  5, 66, 59, 66, 66, 66, 64, 66, 25, 66, 36, 66,
       43, 12, 40], dtype=int32)