In [22]:
import numpy as np # type: ignore

In [23]:
# Sorting

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.sort(a) # sort in ascending
np.sort(a)[::-1] # sort in descending

np.sort(b) # row wise sorting
print(b)
np.sort(b, axis = 0) # row wise sorting 
np.sort(b, axis = 1) # col wise sorting 

[[39  3 87 89]
 [82  3  9 78]
 [31 35 70 20]
 [69 72 96 38]
 [72 34 64 53]
 [85 66 67 12]]


array([[ 3, 39, 87, 89],
       [ 3,  9, 78, 82],
       [20, 31, 35, 70],
       [38, 69, 72, 96],
       [34, 53, 64, 72],
       [12, 66, 67, 85]], dtype=int32)

In [24]:
# Append

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.append(a, 202) # append 202 as last element in a 
print(b.shape[0])
np.append(b, np.ones((b.shape[0], 1)), axis = 1) # append 1 in last col

6


array([[23., 60., 17., 86.,  1.],
       [25., 38., 90., 92.,  1.],
       [51., 26.,  1., 38.,  1.],
       [39., 84., 76., 48.,  1.],
       [35., 91., 65., 96.,  1.],
       [ 9., 12., 84., 22.,  1.]])

In [25]:
# Concatenate

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print(a)
print(b)

np.concatenate((a, b), axis = 0) # row wise -> vstack
np.concatenate((a, b), axis = 1) # col wise -> hstack

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [26]:
# Unique item

a = np.array([1, 2, 1, 2, 4, 5, 6, 5, 7, 9, 7, 3, 2])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [27]:
# Expand dimension

a = np.arange(1, 7).reshape(3, 2)
print(a)
print('\n')
b = np.expand_dims(a, axis = 0)
c = np.expand_dims(a, axis = 1)
# print(a.shape, b.shape)

print(b)
print('\n')
print(c)

[[1 2]
 [3 4]
 [5 6]]


[[[1 2]
  [3 4]
  [5 6]]]


[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [28]:
# Where value satisfy

a = np.random.randint(1, 100, 20)
np.where(a > 50) # return index only value > 50
np.where(a > 50, 0, 1) # replace 0 where true and replace 1 where false

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0])

In [29]:
# Argmax / Argmin -> return max/min value index

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)
np.argmax(a) # max value index
np.argmin(a) # min value index

np.argmax(b, axis = 0)
np.argmin(b, axis = 1)

[12 90 90 27 40 93 17 84 76 48]
[[31 23 73 11]
 [ 1 91 17 47]
 [24 21 28 99]]


array([3, 0, 1])

In [30]:
# Cumsum & Cumprod -> sum of previous all

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.cumsum(a)
np.cumprod(a)

np.cumsum(b, axis = 0) # row
np.cumprod(b, axis = 1) # col

[96 54 95 28 26 62 25 35 60 31]
[[43 92 69 32]
 [ 6 96 79 90]
 [61 12 64 97]]


array([[     43,    3956,  272964, 8734848],
       [      6,     576,   45504, 4095360],
       [     61,     732,   46848, 4544256]])

In [31]:
# Percentile -> how many % people behind me

a = np.random.randint(1, 100, 10)
print(a)

print(np.sort(a))
np.percentile(a, 0) # min
np.percentile(a, 50) # mid
np.percentile(a, 100) # max

[51 56 63 16 49 38 56 31 27 25]
[16 25 27 31 38 49 51 56 56 63]


np.float64(63.0)

In [32]:
# Histogram -> frequency count in given range (bins)
    
a = np.random.randint(1, 100, 50)
print(a)
np.histogram(a, bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

[47 51 68 38  3 76 58 91 16 61 64 59 56 54  3 67  2 56 57 19 43 17 38 62
 23 47 86 27 34 45 56 10 42 51 25 23 17 67 94 18 96 78 83 42 51 17 95 11
 72 86]


(array([ 3,  8,  4,  3,  6, 10,  6,  3,  3,  4]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [33]:
# Corelation (ans lie in -1 to 1) & Coefficient

salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [34]:
# Isin -> search for multiple item

a = np.random.randint(1, 100, 20);
items = np.array([10, 20, 30, 40, 50, 60, 70])

print(a)
print(items)
np.isin(a, items)
a[np.isin(a, items)]

[ 5 23 45 87 69 53 41 53 66 80 40 65 67  3 25 90 87 92 92 26]
[10 20 30 40 50 60 70]


array([40], dtype=int32)

In [35]:
# Flip -> reverse

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.flip(a)
np.flip(b) # row, col flip
np.flip(b, axis = 0) # row flip
np.flip(b, axis = 1) # col flip

[72 86 91 71 92 65 89  4 28 67]
[[80 27 45 27]
 [90 78 44 60]
 [40 60 71 63]]


array([[27, 45, 27, 80],
       [60, 44, 78, 90],
       [63, 71, 60, 40]], dtype=int32)

In [36]:
# Put -> replace specific element

a = np.random.randint(1, 100, 10)
print(a)

np.put(a, [0, 5, 2], [100, 200, 300])
a

[62 59 52 28 35 97 64 24 47 34]


array([100,  59, 300,  28,  35, 200,  64,  24,  47,  34], dtype=int32)

In [37]:
# Delete -> after delete return new array

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.delete(a, 0)
np.delete(a, [0, 2, 3])
np.delete(b, 0, axis = 0)

[ 5 88 78 37 54 81 46 47 72 18]
[[93 80 54 13]
 [92 16 84 86]
 [53 53 64 91]]


array([[92, 16, 84, 86],
       [53, 53, 64, 91]], dtype=int32)

In [38]:
# Set function

m = np.array([1, 2, 3, 4, 5, 6])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)
np.intersect1d(m, n)
np.setdiff1d(m, n) # element in m not n
np.setxor1d(m, n) # remove common element
np.in1d(m, 2)

C:\Users\Asus\AppData\Local\Temp\ipykernel_11764\1598237902.py:10: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m, 2)


array([False,  True, False, False, False, False])

In [39]:
# Clip -> value in range

b = np.random.randint(1, 100, 20)
print(b)
np.clip(b, a_min = 5, a_max = 66)

[42 60 10 81 69 25 35 61 14 69 79 76 65 50 18 69 15 54 39 70]


array([42, 60, 10, 66, 66, 25, 35, 61, 14, 66, 66, 66, 65, 50, 18, 66, 15,
       54, 39, 66], dtype=int32)