In [2]:
import numpy as np

In [80]:
# Sorting

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.sort(a) # sort in ascending
np.sort(a)[::-1] # sort in descending

np.sort(b) # row wise sorting
np.sort(b, axis = 0) # row wise sorting 

array([[24, 13, 17,  4],
       [30, 32, 18,  7],
       [54, 48, 54, 23],
       [69, 55, 60, 28],
       [75, 60, 82, 64],
       [91, 87, 86, 93]])

In [77]:
# Append

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.append(a, 202) # append 202 as last element in a 
print(b.shape[0])
np.append(b, np.ones((b.shape[0], 1)), axis = 1) # append 1 in last col

6


array([[29., 57., 41., 73.,  1.],
       [13., 81., 58.,  3.,  1.],
       [97., 96., 81., 28.,  1.],
       [10., 77., 12., 22.,  1.],
       [79., 10.,  5., 94.,  1.],
       [70., 32.,  5., 59.,  1.]])

In [83]:
# Concatenate

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

np.concatenate((a, b), axis = 0) # row wise
np.concatenate((a, b), axis = 1) # col wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [85]:
# Unique item

a = np.array([1, 2, 1, 2, 4, 5, 6, 5, 7, 9, 7, 3, 2])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [93]:
# Expand dimension

a = np.arange(1, 7).reshape(3, 2)
print(a)
np.expand_dims(a, axis = 0)

[[1 2]
 [3 4]
 [5 6]]


array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [97]:
# Where value satisfy

a = np.random.randint(1, 100, 20)
np.where(a > 50) # return index only value > 50
np.where(a > 50, 0, 1) # replace 0 where true and replace 1 where false

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [104]:
# Argmax Argmin -> return max/min value index

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)
np.argmax(a) # max value index
np.argmin(a) # min value index

np.argmax(b, axis = 0)
np.argmin(b, axis = 1)

[82 30  7 72 92 13 64 44 90 83]
[[42  9 64 77]
 [44 11 82 89]
 [96 60 17 32]]


array([1, 1, 2], dtype=int64)

In [111]:
# Cumsum & Cumprod -> sum of previous all

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.cumsum(a)
np.cumprod(a)

np.cumsum(b, axis = 0) # row
np.cumprod(b, axis = 1) # col

[66 99 26 16 28 46 43 73 88 43]
[[60 27 65 52]
 [ 1 96 27 99]
 [ 4 68 38 87]]


array([[     60,    1620,  105300, 5475600],
       [      1,      96,    2592,  256608],
       [      4,     272,   10336,  899232]])

In [114]:
# Percentile -> how many % people behind me

a = np.random.randint(1, 100, 10)
print(a)

np.percentile(a, 100) # max
np.percentile(a, 0) # min
np.percentile(a, 50) # mid

[13  6 74 48 93 91 84 14 23  2]


35.5

In [116]:
# Histogram -> frequency count in given range (bins)

a = np.random.randint(1, 100, 50)
print(a)
np.histogram(a, bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

[48 34 80 14 65 45  2 59 76 43 21 68 37 41 51 10 24 38 43 68 45 57 89 16
 49 19 88 86 11 40 85 89 46 36 57 10 87 27 87 40 20 96 74 79 83 86 88 58
 96  7]


(array([ 2,  6,  4,  4, 10,  5,  3,  3, 11,  2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [117]:
# Corelation & Coefficient

salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [127]:
# Isin -> search for multiple item

a = np.random.randint(1, 100, 20);
items = np.array([10, 20, 30, 40, 50, 60, 70])

np.isin(a, items)
a[np.isin(a, items)]

array([50, 30])

In [132]:
# Flip -> reverse

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.flip(a)
np.flip(b) # row, col flip
np.flip(b, axis = 0) # row flip
np.flip(b, axis = 1) # col flip

[ 9 71 85 52 65 41 55 24 86 75]
[[73  3  6 83]
 [11 99 20 68]
 [41 30 86 15]]


array([[83,  6,  3, 73],
       [68, 20, 99, 11],
       [15, 86, 30, 41]])

In [135]:
# Put -> replace specific element

a = np.random.randint(1, 100, 10)
print(a)

np.put(a, [0, 1, 2], [100, 200, 300])
a

[28 88 89 38  9 43 73 35 77 93]


array([100, 200, 300,  38,   9,  43,  73,  35,  77,  93])

In [139]:
# Delete -> after delete return new array

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.delete(a, 0)
np.delete(a, [0, 2, 3])
# np.delete(b, 0, axis=0)

[60 66 18 55 45 25 82 77 94 63]
[[68 25 11 74]
 [ 7 15 75 58]
 [28 48 41 74]]


array([66, 45, 25, 82, 77, 94, 63])

In [150]:
# Set function

m = np.array([1, 2, 3, 4, 5, 6])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)
np.intersect1d(m, n)
np.setdiff1d(m, n) # element in m not n
np.setxor1d(m, n) # remove common element
np.in1d(m, 2)

array([False,  True, False, False, False, False])

In [154]:
# Clip -> value in range

a = np.random.randint(1, 100, 20)
print(a)
np.clip(a, a_min = 5, a_max = 66)

[41 40 95 49 36 44 35 41 36 51 32 92 30 74 89 98  7 92 74 71]


array([41, 40, 66, 49, 36, 44, 35, 41, 36, 51, 32, 66, 30, 66, 66, 66,  7,
       66, 66, 66])